name: Update OpenAPI Specification

on:
  schedule:
    # This schedule runs at 00:00 every day. Adjust the cron job timing as necessary.
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Download the latest openapi.yaml
        run: curl -o openai-openapi.yaml https://raw.githubusercontent.com/openai/openai-openapi/master/openapi.yaml
      
      - name: Commit and push if changed
        run: |
          git config --global user.email "louis.beaumont@gmail.com"
          git config --global user.name "louis030195"
          git add openai-openapi.yaml
          git commit -m "Update openai-openapi.yaml" || echo "No changes to commit"
          git push